site_name: Computer Engineering KB
site_url: https://minicla03.github.io/ComputerEngineeringKB/
theme:
  name: material
  icon:
    logo: material/library
  #favicon: assets/favicon.png # Assicurati di avere un file favicon.png in assets
  palette:
    scheme: slate
    primary: indigo
  features:
    - navigation.tabs
    - search.share
    - content.code.copy # Aggiunge il tasto per copiare il codice
    - content.code.annotate # Permette di inserire annotazioni numerate nei blocchi di codice

extra:
  manifest: manifest.webmanifest

exclude_patterns:
  - "*.py"
  - ".github/**/*"
  - "requirements.txt"
  - ".vscode/**/*"

plugins:
  - search
  - roamlinks
  - mermaid2

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite # Per il codice all'interno dei paragrafi
  - pymdownx.snippets # Per includere file di codice esterni
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
