site_name = "Computer Engineering KB"
site_url = "https://minicla03.github.io/ComputerEngineeringKB/"
wikilinks = true

extra_javascript = [
  "https://polyfill.io/v3/polyfill.min.js?features=es6",
  "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
]

[theme]
name = "material"

[theme.palette]
scheme = "slate"
primary = "indigo"

[theme.features]
navigation_tabs = true
code_copy = true

[content]
admonitions = true
diagrams = "mermaid"
wikilinks = true

[build]
docs_dir = "docs"
site_dir = "site"

[markdown_extensions]
"pymdownx.arithmatex" = { generic = true }